### ISSUE TITLE
CSAPP 家庭作业遇到的问题

### ISSUE THREAD

**Issue by tiggerlee** [tiggerlee/exercises#3]
2.73和2.75 没有找到好的解决方法，参考网上的答案也不明白
2.79 题目看不明白
2.82 看了网上的解答，不明白
2.84 B和C不明白
2.85 十进制不会算
2.90 B看了别人的解答，不知道怎么算出来的
2.93 对于exp等于1的时候的特殊处理还没有弄明白
2.94 2.95 2.96还没有做

**Comment by xy521521** [comment]
2.73的意思是没有溢出输出正常值，正溢出输出INT_MAX，负溢出输出INT_MIN.
http://lambda.cool/wiki/doku.php?id=answers:csapp:homework-2.73
